application: chronostriples
version: 0-1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(html|js|css))$
  static_files: static/\1
  upload: static/.*\.(html|js|css)$

- url: /cron/startcrawling
  script: flankers.Scrawler.application

- url: /cron/indexing
  script: flankers.Indexing.application

- url: /cron/n3caching
  script: flankers.extCaching.application

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"

builtins:
- appstats: on
