application: chronostriples
version: 0-1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(html|js|css))$
  static_files: static/\1
  upload: static/.*\.(html|js|css)$

- url: /cron/startcrawling
  script: flankers.scrawler.application
  login: admin

- url: /cron/indexing
  script: flankers.indexing.application
  login: admin

- url: /cron/n3caching
  script: flankers.extCaching.application
  login: admin

- url: /cron/storetweets
  script: flankers.tweetStore.application
  login: admin

- url: /remoteapi
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"
- name: ssl
  version: latest

builtins:
- remote_api: on
- appstats: on
